/*
389. Find the Difference
Easy

2117

356

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        //using add concept -> same cancel each other and additional remains
        
        //we can also sue ascii Sum method -> the diff in sum of ascii of s & t is the ascii of additional char
        
        int sum = 0;
        char[] charsS = s.toCharArray();
        char[] charsT = t.toCharArray();
        
        for (int i = 0; i < charsS.length; i++)
            sum = sum + charsT[i] - charsS[i];
        
        return (char) (sum + charsT[charsT.length - 1]);
    }
}
